export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_OUT = "LOGIN_OUT"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const GET_SMS_CODE_SUCCESS = "GET_SMS_CODE_SUCCESS"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"

export const SHOP_CERTIFICATION_SUCCESS = "SHOP_CERTIFICATION_SUCCESS"
export const SHOP_RE_CERTIFICATION_SUCCESS = "SHOP_RE_CERTIFICATION_SUCCESS"
export const COMPLETE_SHOP_INFO_SUCCESS = "COMPLETE_SHOP_INFO_SUCCESS"
export const PUBLISH_ANNOUNCEMENT_SUCCESS = "PUBLISH_ANNOUNCEMENT_SUCCESS"
export const PUBLISH_SHOP_COMMENT_SUCCESS = "PUBLISH_SHOP_COMMENT_SUCCESS"
export const UPDATE_ANNOUNCEMENT_SUCCESS = "UPDATE_ANNOUNCEMENT_SUCCESS"

export const PROFILE_SUBMIT_SUCCESS = "PROFILE_SUBMIT_SUCCESS"
export const ADD_USER_PROFILE = "ADD_USER_PROFILE"
export const FETCH_PERSONAL_INFO_SUCCESS = "FETCH_PERSONAL_INFO_SUCCESS"
export const PROMOTER_CERTIFICATION_SUCCESS = 'PROMOTER_CERTIFICATION_SUCCESS'

export const FETCH_USER_FOLLOWERS_SUCCESS = 'FETCH_USER_FOLLOWERS_SUCCESS'
export const FETCH_USER_FOLLOWERS_TOTAL_COUNT_SUCCESS = 'FETCH_USER_FOLLOWERS_TOTAL_COUNT_SUCCESS'
export const FETCH_USER_FOLLOWEES_SUCCESS = 'FETCH_USER_FOLLOWEES_SUCCESS'
export const FETCH_USER_FAVORITEARTICLE_SUCCESS = 'FETCH_USER_FAVORITEARTICLE_SUCCESS'
// export const DOCTOR_CERTIFICATION_REQUEST = "DOCTOR_CERTIFICATION_REQUEST"

export const ADD_HEALTH_PROFILE = 'ADD_HEALTH_PROFILE'



