export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_OUT = "LOGIN_OUT"

export const LOGIN_PASSWORD_REQUEST = "LOGIN_PASSWORD_REQUEST"
export const LOGIN_PASSWORD_SUCCESS = "LOGIN_PASSWORD_SUCCESS"
export const LOGIN_PASSWORD_FAILURE = "LOGIN_PASSWORD_FAILURE"

export const LOGIN_PHONE_REQUEST = "LOGIN_PHONE_REQUEST"
export const LOGIN_PHONE_SUCCESS = "LOGIN_PHONE_SUCCESS"
export const LOGIN_PHONE_FAILURE = "LOGIN_PHONE_FAILURE"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const SAVE_PERSONAL_INFO_SUCCESS = "SAVE_PERSONAL_INFO_SUCCESS"
export const GET_RECOMMEND_USERS = "GET_RECOMMEND_USERS"

export const GET_SMS_CODE_REQUEST = "GET_SMS_CODE_REQUEST"
export const GET_SMS_CODE_SUCCESS = "GET_SMS_CODE_SUCCESS"
export const GET_SMS_CODE_FAILURE = "GET_SMS_CODE_FAILURE"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

export const VERIFY_SMS_CODE_REQUEST = "VERIFY_SMS_CODE_REQUEST"
export const VERIFY_SMS_CODE_SUCCESS = "VERIFY_SMS_CODE_SUCCESS"
export const VERIFY_SMS_CODE_FAILURE = "VERIFY_SMS_CODE_FAILURE"

export const FETCH_USERS_INFO = 'FETCH_USERS_INFO'
export const GET_ARTICLE_WORD_COUNT = "GET_ARTICLE_WORD_COUNT"
export const ADD_CORPUS = "ADD_CORPUS"

export const CREATEFAKETOKEN = 'CREATEFAKETOKEN'

export const UPDATEUSERCOVERIMAGEACTION = 'UPDATEUSERCOVERIMAGEACTION'

export const UPDATEUSERHEADIMAGEACTION = 'UPDATEUSERHEADIMAGEACTION'

export const UPDATEUSERSIGN = 'UPDATEUSERSIGN'
export const UPDATEUSERCLASS = 'UPDATEUSERCLASS'
export const UPDATEUSERSCHOOL = 'UPDATEUSERSCHOOL'
export const UPDATEUSERPENNAME = 'UPDATEUSERPENNAME'
export const UPDATEUSERGENDER = 'UPDATEUSERGENDER'

export const HIDE_LAUNCH = 'HIDE_LAUNCH'

export const UPDATE_CORPUS_ARTICLE_COUNT = 'UPDATE_CORPUS_ARTICLE_COUNT'
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL'