export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_OUT = "LOGIN_OUT"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const GET_SMS_CODE_SUCCESS = "GET_SMS_CODE_SUCCESS"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"


export const SHOP_CERTIFICATION_SUCCESS = "SHOP_CERTIFICATION_SUCCESS"

export const PROFILE_SUBMIT_SUCCESS = "PROFILE_SUBMIT_SUCCESS"





