/**
 * Created by zachary on 2016/12/15.
 */

export const UPDATE_CONFIG_BANNERS = 'UPDATE_CONFIG_BANNERS'
export const UPDATE_CONFIG_ANNOUNCEMENT = 'UPDATE_CONFIG_ANNOUNCEMENT'
export const UPDATE_CONFIG_COLUMN = 'UPDATE_CONFIG_COLUMN'
export const UPDATE_CONFIG_TOPIC_CATEGORIES = 'UPDATE_CONFIG_TOPIC_CATEGORIES'
export const UPDATE_CONFIG_SHOP_CATEGORIES = 'UPDATE_CONFIG_SHOP_CATEGORIES'
