/**
 * Created by zachary on 2016/12/15.
 */

export const UPDATE_CONFIG_BANNERS = 'UPDATE_CONFIG_BANNERS'
export const UPDATE_CONFIG_ANNOUNCEMENT = 'UPDATE_CONFIG_ANNOUNCEMENT'
export const UPDATE_CONFIG_COLUMN = 'UPDATE_CONFIG_COLUMN'
export const UPDATE_CONFIG_TOPIC_CATEGORIES = 'UPDATE_CONFIG_TOPIC_CATEGORIES'
export const UPDATE_CONFIG_SHOP_CATEGORIES = 'UPDATE_CONFIG_SHOP_CATEGORIES'
export const FETCH_USER_CURRENT_GEO_SUCCESS = 'FETCH_USER_CURRENT_GEO_SUCCESS'
export const REVERSE_GEO_CODE_SUCCESS = 'REVERSE_GEO_CODE_SUCCESS'
export const UPDATE_GEO_LOCATION = 'UPDATE_GEO_LOCATION'