/**
 * Created by lilu on 2017/4/13.
 */
export const UPDATE_SHOP_PROMOTION_DRAFT = 'UPDATE_SHOP_PROMOTION_DRAFT'
export const DESTROY_SHOP_PROMOTION_DRAFT = 'DESTROY_SHOP_PROMOTION_DRAFT'

export const UPDATE_TOPIC_DRAFT= 'UPDATE_TOPIC_DRAFT'
export const DESTROY_TOPIC_DRAFT= 'DESTROY_TOPIC_DRAFT'