/**
 * Created by yangyang on 2016/12/20.
 */
export const MSG_TEXT = -1
export const MSG_SYSTEM = 1
export const MSG_IMAGE = 2
export const MSG_AUDIO = 3

export const MSG_REVIEW = 4
export const MSG_COMMENT = 5
export const MSG_LIKE = 6
export const MSG_HEARSAY = 7

export const INIT_MESSENGER_CLIENT = 'INIT_MESSENGER_CLIENT'
export const CLOSE_MESSENGER_CLIENT = 'CLOSE_MESSENGER_CLIENT'
export const ON_CONVERSATION_CREATED = 'ON_CONVERSATION_CREATED'
export const ON_ENTER_CONVERSATION = 'ON_ENTER_CONVERSATION'
export const ON_LEAVE_CONVERSATION = 'ON_LEAVE_CONVERSATION'
export const ON_MESSAGE_CREATED = 'ON_MESSAGE_CREATED'
export const ON_MESSAGE_SENTED = 'ON_MESSAGE_SENTED'
export const ON_MESSAGE_RECEIVED = 'ON_MESSAGE_RECEIVED'