/**
 * Created by lilu on 2017/7/4.
 */
// export const Pub = "PUBLISH_SUCCESS"
export const PUBLISH_COMMENT_SUCCESS = "PUBLISH_COMMENT_SUCCESS"
export const FETCH_TOPIC_ADD_COMMENTS = "FETCH_TOPIC_ADD_COMMENTS"
export const FETCH_TOPIC_SET_COMMENTS = "FETCH_TOPIC_SET_COMMENTS"
export const FETCH_COMMENT_ADD_COMMENTS = "FETCH_COMMENT_ADD_COMMENTS"
export const FETCH_COMMENT_SET_COMMENTS = "FETCH_COMMENT_SET_COMMENTS"
export const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS"
export const FETCH_MY_COMMENTS_UPS = "FETCH_MY_COMMENTS_UPS"
export const FETCH_MY_TOPICS_UPS = "FETCH_MY_TOPICS_UPS"
export const UP_COMMENT_SUCCESS = "UP_COMMENT_SUCCESS"
export const UP_TOPIC_SUCCESS = "UP_TOPIC_SUCCESS"
export const FETCH_SET_LOCAL_TOPICS = "FETCH_SET_LOCAL_TOPICS"
export const FETCH_ADD_LOCAL_TOPICS = "FETCH_ADD_LOCAL_TOPICS"
export const FETCH_SET_PICKED_TOPICS = "FETCH_SET_PICKED_TOPICS"
export const FETCH_ADD_PICKED_TOPICS = "FETCH_ADD_PICKED_TOPICS"
export const FETCH_ADD_CATE_TOPICS = "FETCH_ADD_CATE_TOPICS"
export const FETCH_SET_CATE_TOPICS = "FETCH_SET_CATE_TOPICS"
export const FETCH_ADD_MAINPAGE_TOPICS = "FETCH_ADD_MAINPAGE_TOPICS"
export const FETCH_SET_MAINPAGE_TOPICS = "FETCH_SET_MAINPAGE_TOPICS"
export const FETCH_ADD_USER_TOPICS = "FETCH_ADD_USER_TOPICS"
export const FETCH_SET_USER_TOPICS = "FETCH_SET_USER_TOPICS"
export const FETCH_SET_TOPIC_UPS = "FETCH_SET_OPIC_UPS"
export const FETCH_ADD_TOPIC_UPS = "FETCH_ADD_OPIC_UPS"
export const FETCH_PUBLISH_TOPIC_SUCCESS = "FETCH_PUBLISH_TOPIC_SUCCESS"
export const FETCH_UPDATE_TOPIC_SUCCESS = "FETCH_UPDATE_TOPIC_SUCCESS"
export const FETCH_ALL_TOPICS = "FETCH_ALL_TOPICS"



