/**
 * Created by lilu on 2017/7/4.
 */
// export const Pub = "PUBLISH_SUCCESS"
export const PUBLISH_COMMENT_SUCCESS = "PUBLISH_COMMENT_SUCCESS"
export const UPDATE_TOPICS = "UPDATE_TOPICS"
export const UPDATE_TOPIC_COMMENTS = "UPDATE_TOPIC_COMMENTS"
export const LIKE_TOPIC_SUCCESS = "LIKE_TOPIC_SUCCESS"
export const UNLIKE_TOPIC_SUCCESS = "UNLIKE_TOPIC_SUCCESS"
export const FETCH_TOPIC_ADD_COMMENTS = "FETCH_TOPIC_ADD_COMMENTS"
export const FETCH_TOPIC_SET_COMMENTS = "FETCH_TOPIC_SET_COMMENTS"
export const FETCH_COMMENT_ADD_COMMENTS = "FETCH_COMMENT_ADD_COMMENTS"
export const FETCH_COMMENT_SET_COMMENTS = "FETCH_COMMENT_SET_COMMENTS"
export const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS"
export const FETCH_MY_COMMENTS_UPS = "FETCH_MY_COMMENTS_UPS"
export const FETCH_MY_TOPICS_UPS = "FETCH_MY_TOPICS_UPS"