/**
 * Created by yangyang on 2017/3/24.
 */

export const GENERATE_INVITE_CODE = 'GENERATE_INVITE_CODE'
export const CLEAR_INVITE_CODE = 'CLEAR_INVITE_CODE'
export const CERTIFICATE_PROMOTER = 'CERTIFICATE_PROMOTER'
export const UPDATE_PROMOTER_INFO = 'UPDATE_PROMOTER_INFO'
export const SET_ACTIVE_PROMOTER = 'SET_ACTIVE_PROMOTER'
export const UPDATE_TENANT_FEE = 'UPDATE_TENANT_FEE'
export const UPDATE_UPPROMOTER_ID = 'UPDATE_UPPROMOTER_ID'
export const SET_MY_TEAM = 'SET_MY_TEAM'
export const ADD_MY_TEAM = 'ADD_MY_TEAM'