/**
 * Created by yangyang on 2017/3/24.
 */

export const GENERATE_INVITE_CODE = 'GENERATE_INVITE_CODE'
export const CLEAR_INVITE_CODE = 'CLEAR_INVITE_CODE'
export const CERTIFICATE_PROMOTER = 'CERTIFICATE_PROMOTER'
export const UPDATE_PROMOTER_INFO = 'UPDATE_PROMOTER_INFO'
export const SET_ACTIVE_PROMOTER = 'SET_ACTIVE_PROMOTER'
export const SET_USER_PROMOTER_MAP = 'SET_USER_PROMOTER_MAP'
export const UPDATE_TENANT_FEE = 'UPDATE_TENANT_FEE'
export const UPDATE_UPPROMOTER_ID = 'UPDATE_UPPROMOTER_ID'
export const SET_PROMOTER_TEAM = 'SET_PROMOTER_TEAM'
export const ADD_PROMOTER_TEAM = 'ADD_PROMOTER_TEAM'
export const SET_PROMOTER_SHOPS = 'SET_PROMOTER_SHOPS'
export const ADD_PROMOTER_SHOPS = 'ADD_PROMOTER_SHOPS'
export const UPDATE_PROMOTER_PERFORMANCE = 'UPDATE_PROMOTER_PERFORMANCE'