/**
 * Created by yangyang on 2017/3/24.
 */
export const CERTIFICATE_PROMOTER = 'CERTIFICATE_PROMOTER'
export const UPDATE_PROMOTER_INFO = 'UPDATE_PROMOTER_INFO'
export const GENERATE_INVITE_CODE = 'GENERATE_INVITE_CODE'
export const SET_ACTIVE_PROMOTER = 'SET_ACTIVE_PROMOTER'