/**
 * Created by zachary on 2017/3/3.
 */

export const UPDATE_LOCAL_DEVICE_TOKEN = 'UPDATE_LOCAL_DEVICE_TOKEN'
export const UPDATE_SYSTEM_NOTICE = 'UPDATE_SYSTEM_NOTICE'
export const UPDATE_SYSTEM_NOTICE_AS_MARK_READED = 'UPDATE_SYSTEM_NOTICE_AS_MARK_READED'
