/**
 * Created by zachary on 2016/12/15.
 */

export const UPDATE_SHOP_LIST = 'UPDATE_SHOP_LIST'
export const UPDATE_PAGING_SHOP_LIST = 'UPDATE_PAGING_SHOP_LIST'
export const UPDATE_SHOP_ANNOUNCEMENT_LIST = 'UPDATE_SHOP_ANNOUNCEMENT_LIST'
export const FOLLOW_SHOP_SUCCESS = 'FOLLOW_SHOP_SUCCESS'
export const UPDATE_USER_FOLLOW_SHOPS_INFO = 'UPDATE_USER_FOLLOW_SHOPS_INFO'
export const SUBMIT_SHOP_COMMENT_SUCCESS = 'SUBMIT_SHOP_COMMENT_SUCCESS'
export const FETCH_SHOP_COMMENT_LIST_SUCCESS = 'FETCH_SHOP_COMMENT_LIST_SUCCESS'
export const FETCH_PAGING_SHOP_COMMENT_LIST_SUCCESS = 'FETCH_PAGING_SHOP_COMMENT_LIST_SUCCESS'
export const FETCH_SHOP_COMMENT_TOTAL_COUNT_SUCCESS = 'FETCH_SHOP_COMMENT_TOTAL_COUNT_SUCCESS'
export const UPDATE_USER_UP_SHOP_INFO = 'UPDATE_USER_UP_SHOP_INFO'
export const USER_UP_SHOP_SUCCESS = 'USER_UP_SHOP_SUCCESS'
export const USER_UNUP_SHOP_SUCCESS = 'USER_UNUP_SHOP_SUCCESS'
export const REPLY_SHOP_COMMENT_SUCCESS = 'REPLY_SHOP_COMMENT_SUCCESS'
export const FETCH_SHOP_COMMENT_REPLY_LIST_SUCCESS = 'FETCH_SHOP_COMMENT_REPLY_LIST_SUCCESS'
export const FETCH_SHOP_COMMENT_UPED_USER_LIST_SUCCESS = 'FETCH_SHOP_COMMENT_UPED_USER_LIST_SUCCESS'
export const USER_UP_SHOP_COMMENT_SUCCESS = 'USER_UP_SHOP_COMMENT_SUCCESS'
export const USER_UNUP_SHOP_COMMENT_SUCCESS = 'USER_UNUP_SHOP_COMMENT_SUCCESS'
export const FETCH_SHOP_TAGS_SUCCESS = 'FETCH_SHOP_TAGS_SUCCESS'