/**
 * Created by zachary on 2016/12/15.
 */

export const UPDATE_SHOP_LIST = 'UPDATE_SHOP_LIST'
export const UPDATE_PAGING_SHOP_LIST = 'UPDATE_PAGING_SHOP_LIST'
export const UPDATE_SHOP_ANNOUNCEMENT_LIST = 'UPDATE_SHOP_ANNOUNCEMENT_LIST'
export const FOLLOW_SHOP_SUCCESS = 'FOLLOW_SHOP_SUCCESS'
