/**
 * Created by zachary on 2016/12/15.
 */

export const UPDATE_SHOP_LIST = 'UPDATE_SHOP_LIST'
export const UPDATE_PAGING_SHOP_LIST = 'UPDATE_PAGING_SHOP_LIST'
export const UPDATE_SHOP_ANNOUNCEMENT_LIST = 'UPDATE_SHOP_ANNOUNCEMENT_LIST'
export const FOLLOW_SHOP_SUCCESS = 'FOLLOW_SHOP_SUCCESS'
export const UPDATE_USER_FOLLOW_SHOPS_INFO = 'UPDATE_USER_FOLLOW_SHOPS_INFO'
export const SUBMIT_SHOP_COMMENT_SUCCESS = 'SUBMIT_SHOP_COMMENT_SUCCESS'
export const FETCH_SHOP_COMMENT_LIST_SUCCESS = 'FETCH_SHOP_COMMENT_LIST_SUCCESS'
export const FETCH_SHOP_COMMENT_TOTAL_COUNT_SUCCESS = 'FETCH_SHOP_COMMENT_TOTAL_COUNT_SUCCESS'
