export const PUBLISH_SUCCESS = "PUBLISH_SUCCESS"
export const PUBLISH_COMMENT_SUCCESS = "PUBLISH_COMMENT_SUCCESS"
export const UPDATE_TOPICS = "UPDATE_TOPICS"
export const UPDATE_TOPIC_COMMENTS = "UPDATE_TOPIC_COMMENTS"