/**
 * Created by yangyang on 2016/12/3.
 */

export const INPUTFORM_INIT_STATE = "INPUTFORM_INIT_STATE"
export const INPUTFORM_ON_CHANGE = "INPUTFORM_ON_CHANGE"
export const INPUTFORM_DESTROY = "INPUTFORM_DESTROY"
export const INPUTFORM_VALID_CHECK = "INPUTFORM_VALID_CHECK"