/**
 * Created by yangyang on 2016/12/3.
 */

export const INPUTFORM_INIT_STATE = "INPUTFORM_INIT_STATE"
export const INPUTFORM_ON_CHANGE = "INPUTFORM_ON_CHANGE"
export const INPUTFORM_DESTROY = "INPUTFORM_DESTROY"
export const INPUTFORM_VALID_CHECK = "INPUTFORM_VALID_CHECK"


//search

export const SEARCH_INIT_STATE = "SEARCH_INIT_STATE"
export const SEARCH_ALL = "SEARCH_ALL"
export const SEARCH_CLEAR = "SEARCH_CLEAR"
export const SEARCH_USER = "SEARCH_USER"
export const SEARCH_USER_CLEAR = "SEARCH_USER_CLEAR"
export const SEARCH_SHOP = "SEARCH_SHOP"
export const SEARCH_SHOP_CLEAR = "SEARCH_SHOP_CLEAR"
export const SEARCH_TOPIC = "SEARCH_TOPIC"
export const SEARCH_TOPIC_CLEAR = "SEARCH_TOPIC_CLEAR"