platform :ios, '8.0'

target "HLife" do
	pod 'RSKImageCropper'
	pod 'QBImagePickerController'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'React', :path => '../node_modules/react-native'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    pod 'Pingpp/Alipay'
    pod 'Pingpp/Wx'
end
